[Settings]
webhook_n8n = http://mrzolzyoutube.mooo.com:5678/webhook/c660fa3d-f769-48b1-9009-2880629a633b/chat
# Пояснялка:Модели OpenWakeWord предзагружены в Docker-образе на этапе сборки
openwakeword_download_models = downloaded
requesttimeout = 120
requestretries = 2

[Commands]
cmd_exit = ["стоп", "stop", "выключись", "вырубись", "выход", "выйти из кванта", "отбой", "отключить питание", "отключи питание", "питание на ноль"]

[Speech]
timeoutspeechrecognition = 8
language = ru-RU
mintextchars = 3

[Vad]
aggressiveness = 2
framems = 30
prerollms = 300
startspeechms = 150
minspeechms = 450
endsilencems = 900
commandtimeout = 15
tailpaddingms = 250
