[Settings]
webhook_n8n = 
# Пояснялка:Модели OpenWakeWord предзагружены в Docker-образе на этапе сборки
openwakeword_download_models = downloaded

[Commands]
cmd_exit = ["стоп", "stop", "выключись", "вырубись", "выход", "выйти из кванта", "отбой", "отключить питание", "отключи питание", "питание на ноль"]

[Speech]
timeoutspeechrecognition = 8

